### ISSUE TITLE
SpriteAnimated Event Driven

### ISSUE THREAD

**Issue by herux** [skycoin/cx-game#261]
I think we need an event, on every struct or package that is required.
for example Animated Slime, it has some action like "Idle" "Jump" or "Dead", we need a listening event from Agents, that  tell Slime to act "Jump" or even "Dead" then call `slime.Action("Dead")`

**Comment by ted537** [comment]
Death is a bit of a poor example for the need to add events, since most (if not all) agents will need to handle death. Additionally, the idle/jump states would make the most sense to be managed internally by the slime component.

Are there any use cases where an external component (non-slime related in this example) would need to send a specific event to a slime?

**Comment by herux** [comment]
yes, I mean not dead's Slime. set Slime action as Jump, when its need to jump
We can change SpiderDrill as an example as well,  when it's drilling, idle if they doing nothing

**Comment by ted537** [comment]
https://github.com/skycoin/cx-game/blob/2b05a024e76e6b8db2f117f781ad4cbbca128522/components/agents/agent_ai/leap.go#L23

Is this the functionality you're looking for?

**Comment by herux** [comment]
it seems so
