### ISSUE TITLE
use z culling to draw objects

### ISSUE THREAD

**Issue by Planutim** [skycoin/cx-game#284]
terrain has to be drawn back to front, other stuff (particles, agents) should have z-order

**Comment by ted537** [comment]
Terrain should probably be drawn front-to-back with z-order. This lets us skip rendering bg tiles when a solid tile exists overtop.

**Comment by ted537** [comment]
While we're at it, now would probably be a good time to refactor sprite rendering. 

We should probably reduce the quantity of `DrawSprite()` style functions.

If sprites were queued up rather than drawn immediately, then we could bind once per texture atlas (or even less if we use other texture units). This could render the custom world shader program unnecessary and thereby reduce code duplication.

In addition, queuing and then flushing sprite rendering would enable the pattern of render solid objects front-to-back followed by transparent objects back-to-front.

**Comment by Planutim** [comment]
yeah we need to sort solid from transparent before drawing. Solid textures need to be having z-order
